### ISSUE TITLE
Confused about the dependency

### ISSUE THREAD

**Issue by theogravity** [HASEL-UZH/PA.UserInputTracker#6]
This package uses `hasel-io-lib` but the readme mentions that you had to create `uiohook-napi` to fix issues with mac. Why doesn't this package use the fork?

**Comment by casaout** [comment]
Apologies for the late reply. Completely missed the issue. We are using a fork [`hasel-io-lib`](https://github.com/HASEL-UZH/uiohook-napi) of the [`uihook-napi`](https://github.com/SnosMe/uiohook-napi) that contains two "fixes" in the `PA.UserInputTracker`. It's explained in a bit more detail under [known issues](https://github.com/HASEL-UZH/PA.UserInputTracker/blob/main/typescript/README.md#known-issues) in the readme. 
Unfortunately, this "fix" only works slightly better, but still causes crashes on macOS (not on Windows). Also it seems that the original library and the forked [`uihook-napi`](https://github.com/SnosMe/uiohook-napi) are not really actively developed anymore.

We will at some point try to build our own io-hook library, but are not sure yet about a timeline. 
If you find a better solution, please do let me know.

And sorry again for the late reply, @theogravity!
